# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: node
    steps:
      - checkout
      - run: echo 'This is the build step'
  test:
    docker:
      - image: alpine
    steps:
      - checkout
      - run: echo 'This is the test step'

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build